//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VpetChatWithOllama.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VpetChatWithOllama.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Prompt 的本地化字符串。
        /// </summary>
        public static string AdvancedPrompt {
            get {
                return ResourceManager.GetString("AdvancedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API URL 的本地化字符串。
        /// </summary>
        public static string APIURL {
            get {
                return ResourceManager.GetString("APIURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat History 的本地化字符串。
        /// </summary>
        public static string ChatHistory {
            get {
                return ResourceManager.GetString("ChatHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Memory 的本地化字符串。
        /// </summary>
        public static string ClearMemory {
            get {
                return ResourceManager.GetString("ClearMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Name 的本地化字符串。
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt 的本地化字符串。
        /// </summary>
        public static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Settings 的本地化字符串。
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Thinking Process 的本地化字符串。
        /// </summary>
        public static string ShowThinkingProcess {
            get {
                return ResourceManager.GetString("ShowThinkingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 use stream 的本地化字符串。
        /// </summary>
        public static string UseStream {
            get {
                return ResourceManager.GetString("UseStream", resourceCulture);
            }
        }
    }
}
